// <auto-generated />
namespace FinalProjectSocialzR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class blackliststatic9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(blackliststatic9));
        
        string IMigrationMetadata.Id
        {
            get { return "201706231915042_blackliststatic9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
